name: Build
on:
  push:
    paths-ignore:
      - example/**
      - README.md
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - example/**
      - README.md
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for Objective-C files.
      uses: jidicula/clang-format-action@v4.8.0
      with:
        clang-format-version: '13'
  build:
    needs: formatting-check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macOS-13
        go:
        - '^1.20'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - name: vet
        run: go vet ./...
      - name: Download Linux kernel
        run: make download_kernel
      - name: Unit Test
        run: make test
      - name: Build Linux
        run: make -C example/linux
      - name: Build GUI Linux
        run: make -C example/gui-linux
